#! /bin/sh

bspc config border_width         4
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config initial_polarity second_child

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

# colors
bspc config active_border_color "#37c3d6"
bspc config focused_border_color "#37c3d6"
bspc config presel_feedback_color "#888888"

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a chromium desktop=^1 follow=on
bspc rule -a jetbrains-studio desktop=^3 state=floating follow=on #android studio

panel &
