#! /bin/sh

bspc config border_width         4

bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  false
bspc config initial_polarity second_child
bspc config click_to_focus		true
bspc config pointer_modifier	mod4

workspaces_multimonitor.sh

#bspc monitor LVDS1 -d 1 2 3 4 5 6
#bspc monitor HDMI1 -d 7 8 9 10 11 12

# colors
bspc config normal_border_color "#262626"
bspc config active_border_color "#CB07B0"
bspc config focused_border_color "#CB07B0"
bspc config presel_feedback_color "#888888"

bspc rule -a mpv desktop=focused follow=on state=floating
bspc rule -a tk follow=off state=floating
bspc rule -a Tk follow=off state=floating
bspc rule -a anki follow=on state=floating
bspc rule -a Anki follow=on state=floating

#focusborder.sh
autogap.sh &
~/.config/polybar/launch.sh &

