#! /bin/sh

if [ -z "$WM_GAP" ]; then export WM_GAP=10; fi

bspc config border_width         4
bspc config window_gap           $WM_GAP

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config initial_polarity second_child

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 一 二 三 四 五 六 七

# colors
bspc config active_border_color "#37c3d6"
bspc config focused_border_color "#37c3d6"
bspc config presel_feedback_color "#888888"

bspc rule -a chromium desktop=^1 follow=on
bspc rule -a mpv desktop=focused follow=on state=floating
bspc rule -a tk follow=off state=floating
bspc rule -a Tk follow=off state=floating

panel &
